### ISSUE TITLE
Unexpected reads behavior for scientific

### ISSUE THREAD

**Issue by timbod7** [basvandijk/scientific#21]
My parsing code fails because reads for scientific has different behaviour to the builtin types:

    $ ghci
    GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
    Loading package ghc-prim ... linking ... done.
    Loading package integer-gmp ... linking ... done.
    Loading package base ... linking ... done.
    Prelude> reads "" :: [(Int,String)]
    []
    Prelude> reads "" :: [(Double,String)]
    []
    Prelude> reads "" :: [(Data.Scientific.Scientific,String)]
    Loading package array-0.5.0.0 ... linking ... done.
    Loading package deepseq-1.3.0.2 ... linking ... done.
    Loading package bytestring-0.10.4.0 ... linking ... done.
    Loading package text-1.1.0.0 ... linking ... done.
    Loading package hashable-1.2.2.0 ... linking ... done.
    Loading package scientific-0.3.3.1 ... linking ... done.
    [(0.0,"")]
    Prelude> 

Is this intended?

**Comment by basvandijk** [comment]
This is fixed in [0.3.3.7](http://hackage.haskell.org/package/scientific-0.3.3.7).
