### ISSUE TITLE
'/' diverges even if its output is finite.

### ISSUE THREAD

**Issue by neongreen** [basvandijk/scientific#23]
> 0.6/0.3 :: Scientific
    ^CInterrupted.

The reason is that it's implemented using `recip`, which diverges for `0.3`.

**Comment by basvandijk** [comment]
Thanks for the bug report!

**Comment by basvandijk** [comment]
I released [scientific-0.3.3.6](http://hackage.haskell.org/package/scientific-0.3.3.6) with a fix.
