### ISSUE TITLE
Cannot divide one by nine

### ISSUE THREAD

**Issue by jaspervdj** [basvandijk/scientific#38]
Trying to divide one by nine just hangs and eats a CPU core at 100%:

```
jasper@colony6 ~> ghci
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> :m +Data.Scientific 
Prelude Data.Scientific> (1.0 :: Scientific) / (9.0 :: Scientific)
```

Version:

```
jasper@colony6 ~/D/L/ludwig (develop)> ghc-pkg list | grep scientific
    scientific-0.3.4.4
```

**Comment by jaspervdj** [comment]
Ah, just noticed this in the README:

> WARNING: Although Scientific is an instance of Fractional, the methods are only partially defined! Specifically recip and / will diverge (i.e. loop and consume all space) when their outputs have an infinite decimal expansion. fromRational will diverge when the input Rational has an infinite decimal expansion. Consider using fromRationalRepetend for these rationals which will detect the repetition and indicate where it starts.

**Comment by basvandijk** [comment]
Sorry to have heat up your CPU ;-)

The partial methods are unfortunate but I need an instance of Fractional to allow literal Scientific values because they use the `fromRational` method.
