### ISSUE TITLE
Flooring a big number returns 0?

### ISSUE THREAD

**Issue by nh2** [basvandijk/scientific#39]
```
> import Data.Scientific
> read "1e100" :: Scientific
1.0e100
> floor (read "1e100" :: Scientific) :: Int
0
```

What's going on?

The comment at https://hackage.haskell.org/package/scientific-0.3.4.4/docs/src/Data-Scientific.html#line-208 says

`-- | @'floor' s@ returns the greatest integer not greater than @s@`

That doesn't seem to be true.

**Comment by nh2** [comment]
1^100 `mod` 2^64 is 0, so the result makes sense, but the comment doesn't.

**Comment by basvandijk** [comment]
What is happening internally is:

```haskell
fromInteger (10^100 :: Integer) :: Int
0
```

Maybe I should make the documentation more specific like:

    -- | @'floor' s@ returns `fromInteger` applied to the greatest Integer not greater than @s@

What do you think?

**Comment by basvandijk** [comment]
Since this isn't user facing documentation it's not that important to be fully formal.
