### ISSUE TITLE
Missing support for GHC 8.2.1

### ISSUE THREAD

**Issue by asr** [basvandijk/scientific#49]
I got an error related to the base library when using GHC 8.2.1 RC1. Bumped upper bound version of base to 4.11 fixed the issue.

CC'ing @jonaprieto.

**Comment by basvandijk** [comment]
I released [scientific-0.3.4.12](http://hackage.haskell.org/package/scientific-0.3.4.12) which support `base-4.10`.

**Comment by asr** [comment]
Great! Thanks!
