### ISSUE TITLE
Making `scientificP` public.

### ISSUE THREAD

**Issue by shlok** [basvandijk/scientific#51]
In [/src/Data/Scientific.hs](https://github.com/basvandijk/scientific/blob/770e7db512aa0afd2b58b472d30599e9e685f58f/src/Data/Scientific.hs), we find the parser `scientificP :: ReadP Scientific`.

To use this parser in my own program, I ended up manually copying the parser’s code out. It would have been nice if it had been directly available from `Data.Scientific`.

What do you think about exposing this parser to the public?

**Comment by basvandijk** [comment]
Hi @shlok, If you have a use for `scientificP` I wouldn't mind having it exposed.

Care to submit a PR?

**Comment by shlok** [comment]
Hi @basvandijk. Do you think it would be worthwhile if we (or I) added unit tests for the examples that we recently added to the documentation for the [`Read` instance](https://github.com/basvandijk/scientific/pull/52/commits/435bd50357555cb9e0e4e2f938023c30bd31a8a9) and [`scientificP`](https://github.com/basvandijk/scientific/pull/52/commits/ed34892a679f7d859f5376bb3afe2e2968ae9ce9)? (Just to make sure that actual results will never deviate from these documented examples.)

**Comment by basvandijk** [comment]
Hey @shlok, note that we already have a few parser unit tests but there's no problem adding a few more. Go ahead.
