### ISSUE TITLE
Design of fromRationalRepetend

### ISSUE THREAD

**Issue by seagreen** [basvandijk/scientific#58]
Currently:
```
-- If the limit is not reached or no limit was specified @Right (s,
-- mbRepetendIx)@ will be returned.
<...>
fromRationalRepetend
    :: Maybe Int -- ^ Optional limit
    -> Rational
    -> Either (Scientific, Rational) (Scientific, Maybe Int)
```
This forces the caller to handle a `Right` result even the caller knows that will never happen because they used `Nothing` to specify no limit.

What about breaking it into two functions?
```
fromRationalFoo -- Not sure about the names
    :: Int -- ^ Limit
    -> Rational
    -> Either (Scientific, Rational) (Scientific, Maybe Int)
```
and
```
fromRationalBar :: Rational -> (Scientific, Maybe Int)
```

**Comment by basvandijk** [comment]
We should keep `fromRationalRepetend` in order not to break backwards compatibility. Some possible names for the two new functions:

* `fromRationalRepetendWithLimit` and `fromRationalRepetendWithNoLimit`
* `fromRationalRepetendLimit` and `fromRationalRepetendNoLimit`
* `fromRationalRepetendLimited` and `fromRationalRepetendUnlimited`
* `limitedFromRationalRepetend` and `unlimitedFromRationalRepetend`

Any preferences or other ideas?

**Comment by seagreen** [comment]
I like `fromRationalRepetendLimited` and `fromRationalRepetendUnlimited`, but any of the `fromRationalRepetend*` options sound good to me.

No other ideas at the moment, but I'll keep an eye out. Thanks for the great library!

**Comment by seagreen** [comment]
Awesome! Thanks again for your hard work:)
