### ISSUE TITLE
Support for QuickCheck 2.11.x?

### ISSUE THREAD

**Issue by peti** [basvandijk/scientific#60]
Trying to build things with GHC 8.4.1 is difficult unless one uses the latest version of QuickCheck (mostly because doctest and hspec require it). Would it be possible to get an update of this package that supports QC version 2.11.x?

**Comment by basvandijk** [comment]
[scientific-0.3.5.2-r5](http://hackage.haskell.org/package/scientific-0.3.5.2/revisions/) now has support for QuickCheck-2.11.

**Comment by peti** [comment]
Thank you.
