### ISSUE TITLE
add Floating support

### ISSUE THREAD

**Issue by KiaraGrouwstra** [basvandijk/scientific#74]
presently quite some mathematical operations are defined on the [Floating](https://hackage.haskell.org/package/base-4.14.1.0/docs/Prelude.html#t:Floating) typeclass.
would you be willing to take a PR adding support for this extra functionality?

**Comment by phadej** [comment]
I don't see how they would work.

**Comment by KiaraGrouwstra** [comment]
i'm not sure how to implement things like exp/log/sin on `Scientific` yet either, but if we're at the question of implementation already then that sounds like progress i guess. :)

**Comment by phadej** [comment]
I think that they don't have reasonable implementations, that's why I asked. You would need to pick some arbitrary precision and that doesn't sound like a good idea. I there are other option or a clever trick, I'm curious to hear about tit!

**Comment by KiaraGrouwstra** [comment]
i'm not sure i have the answers.
until we have indication there is a solution here, perhaps i should mark this as closed, given this doesn't presently seem actionable from an implementation standpoint.
