### ISSUE TITLE
Build failed due to `version 'GLIBC_2.29' not found`

### ISSUE THREAD

**Issue by July541** [basvandijk/scientific#78]
While I built [HLS](https://github.com/haskell/haskell-language-server) it was failed and the log shows that 

> /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/wind/.cabal/store/ghc-8.10.4/scientific-0.3.7.0-5901ae22c4e769e234067841b4fb17409c22d0f303e4ec5816e53922ab14c0fc/lib/libHSscientific-0.3.7.0-5901ae22c4e769e234067841b4fb17409c22d0f303e4ec5816e53922ab14c0fc-ghc8.10.4.so)

OS: Ubuntu 18.04.5 LTS
kernel: 5.4.72-microsoft-standard-WSL2

**Comment by phadej** [comment]
I have seen this error only when running programs compiled against newer glibc on systems with older glibc. I don't think this is `secientifc`s issue.

**Comment by July541** [comment]
> I have seen this error only when running programs compiled against newer glibc on systems with older glibc. I don't think this is `secientifc`s issue.

It's ok after I upgrade to Ubuntu 20 indeed.
